server:
  port: 8001
  #  servlet:
  #    context-path: /cloud-provider-payment

spring:
  profiles:
    active: test2
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.222.58.122:3307/learn_springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.imoder.springcloud.entities.po


eureka:
  instance:
    instance-id: payment${server.port}
    # 显示访问路径
    prefer-ip-address: on
    # 设置本客户端发送心跳的频率
    lease-renewal-interval-in-seconds: 5
    # 设置服务端在未收到本服务端心跳多长时间之后将本客户端置为无效
    lease-expiration-duration-in-seconds: 10

  client:
    # 表示将自己作为一个 eureka 客户端注入到 eureka server 中去
    register-with-eureka: on
    # 表示将从 eureka server 中抓取自己的信息,默认为 true, 单点无所谓,集群必须设置为 true 才能配合 ribbon使用 lb
    fetch-registry: on
    service-url:
      # default-zone 不行!
      # 单机版
      # defaultZone: http://eureka7001.com:7001/eureka
      # eureka地址
      defaultZone: http://124.222.58.122:7001/eureka
      # 集群版
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


logging:
  level:
    cn.imoder.springcloud: info
  pattern:
    dateformat: HH:mm:ss:SSS