name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
      
      - name: lslslsls
        run: |
          ls -lah ${{ github.workspace }}/../
      - run: echo "--------------"
      - run: ls ./
      - run: echo "--------------"
      - run: ls /
      - run: echo "--------------"
      - run: ls /tmp/
        
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{github.repository}}:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
